<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Tutu-PC" name="Learning assertions" tests="1" failures="1" timestamp="15 May 2016 12:34:15 GMT" time="0.397" errors="0">
  <testcase name="testGoogleSearch" time="0.158" classname="tests.UsingAssertions">
    <failure type="java.lang.AssertionError" message="Error coming because of xyz reason expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Error coming because of xyz reason expected [true] but found [false]
	at tests.UsingAssertions.testGoogleSearch(UsingAssertions.java:25)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- testGoogleSearch -->
</testsuite> <!-- Learning assertions -->
